language: node_js
services:
  - docker
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME_PRD=microservices-shop
    - DOCKER_IMAGE_NAME=frontend-node

  deploy:
  - provider: script
    script: ./deploy-production.sh
    skip_cleanup: true

