language: node_js
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_23be3aed30c7_key -iv $encrypted_23be3aed30c7_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - gcloud auth activate-service-account --key-file client-secret.json
  - gcloud docker -- push gcr.io/microsevices-shop/frontend-node:v1

